// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderItems struct {
	ID        int64              `json:"id"`
	OrderID   int64              `json:"order_id"`
	ProductID int64              `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	UnitPrice int64              `json:"unit_price"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Orders struct {
	ID          int64              `json:"id"`
	Status      string             `json:"status"`
	TotalAmount int64              `json:"total_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	UserID      pgtype.Int8        `json:"user_id"`
}

type Products struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Price         int64              `json:"price"`
	StockQuantity int32              `json:"stock_quantity"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Users struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
