// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (status, total_amount, user_id)
VALUES ($1, $2, $3)
RETURNING id, status, total_amount, created_at, updated_at, cancelled_at, user_id
`

type CreateOrderParams struct {
	Status      string      `json:"status"`
	TotalAmount int64       `json:"total_amount"`
	UserID      pgtype.Int8 `json:"user_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.Status, arg.TotalAmount, arg.UserID)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.UserID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, unit_price, created_at
`

type CreateOrderItemParams struct {
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	UnitPrice int64 `json:"unit_price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItems, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItems
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, status, total_amount, created_at, updated_at, cancelled_at, user_id FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Orders, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.UserID,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, status, total_amount, created_at, updated_at, cancelled_at, user_id FROM orders
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id int64) (Orders, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.UserID,
	)
	return i, err
}

const listOrderItemsByOrderId = `-- name: ListOrderItemsByOrderId :many
SELECT id, order_id, product_id, quantity, unit_price, created_at FROM order_items
WHERE order_id = $1
ORDER BY id ASC
`

func (q *Queries) ListOrderItemsByOrderId(ctx context.Context, orderID int64) ([]OrderItems, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItems
	for rows.Next() {
		var i OrderItems
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, status, total_amount, created_at, updated_at, cancelled_at, user_id FROM orders
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserIDParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Orders, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orders
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, cancelled_at = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, status, total_amount, created_at, updated_at, cancelled_at, user_id
`

type UpdateOrderStatusParams struct {
	ID          int64              `json:"id"`
	Status      string             `json:"status"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Orders, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.CancelledAt)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
		&i.UserID,
	)
	return i, err
}
