// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, price, stock_quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, price, stock_quantity, created_at, updated_at
`

type CreateProductParams struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Price         int64  `json:"price"`
	StockQuantity int32  `json:"stock_quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Products, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
	)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, price, stock_quantity, created_at, updated_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Products, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, name, description, price, stock_quantity, created_at, updated_at FROM products
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetProductForUpdate(ctx context.Context, id int64) (Products, error) {
	row := q.db.QueryRow(ctx, getProductForUpdate, id)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsForUpdate = `-- name: GetProductsForUpdate :many
SELECT id, name, description, price, stock_quantity, created_at, updated_at FROM products
WHERE id = ANY($1::bigint[])
ORDER BY id ASC
FOR UPDATE
`

func (q *Queries) GetProductsForUpdate(ctx context.Context, dollar_1 []int64) ([]Products, error) {
	rows, err := q.db.Query(ctx, getProductsForUpdate, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Products
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, stock_quantity, created_at, updated_at FROM products
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Products, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Products
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, description = $3, price = $4, stock_quantity = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, price, stock_quantity, created_at, updated_at
`

type UpdateProductParams struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Price         int64  `json:"price"`
	StockQuantity int32  `json:"stock_quantity"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Products, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
	)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock_quantity = stock_quantity + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, price, stock_quantity, created_at, updated_at
`

type UpdateProductStockParams struct {
	ID            int64 `json:"id"`
	StockQuantity int32 `json:"stock_quantity"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Products, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.StockQuantity)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
