// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItems, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Products, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetOrder(ctx context.Context, id int64) (Orders, error)
	GetOrderForUpdate(ctx context.Context, id int64) (Orders, error)
	GetProduct(ctx context.Context, id int64) (Products, error)
	GetProductForUpdate(ctx context.Context, id int64) (Products, error)
	GetProductsForUpdate(ctx context.Context, dollar_1 []int64) ([]Products, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id int64) (Users, error)
	ListOrderItemsByOrderId(ctx context.Context, orderID int64) ([]OrderItems, error)
	ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Orders, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Products, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Orders, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Products, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Products, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
